# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

spring:
  application:
    name: demo-app
  jpa:
    # Disable the DDL handling by Hibernate
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      javax:
        persistence:
          query:
            timeout: ${app.transaction-timeout-in-milliseconds} # Global JPA query timeout (in milliseconds)
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        connection:
          isolation: 2 # READ_COMMITTED
  transaction:
    default-timeout: ${app.transaction-timeout-in-seconds} # Global transaction timeout (in seconds)
logging:
  level:
    root: error
    com.amazon.aws: info
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
server:
  error:
    include-message: on_param
    include-binding-errors: never
    whitelabel:
      enabled: false
  max-http-request-header-size: 8KB
  netty:
    connection-timeout: ${app.server-timeout-in-milliseconds}
    idle-timeout: ${app.server-timeout-in-milliseconds}
  tomcat:
    connection-timeout: ${app.server-timeout-in-milliseconds}
    keep-alive-timeout: ${app.server-timeout-in-milliseconds}
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
app:
  server-timeout-in-milliseconds: 60000
  transaction-timeout-in-seconds: 15
  transaction-timeout-in-milliseconds: 15000
  # Token Bucket BackOff Retry with Simple Retry
  initial-retry-delay-in-milliseconds: 1000
  max-retry-delay-in-milliseconds: 5000
  retry-backoff-multiplier: 2.0
  retry-permits-per-second: 1.0
  retry-timeout-in-seconds: 30
  # Simple Retry for limiting max attempts
  max-retry-attempts: 10